# Generated by Django 6.0 on 2025-12-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_mcp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcptoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Token expiration date (leave empty for indefinite tokens)', null=True),
        ),
    ]
