# Generated by Django 6.0.1 on 2026-01-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_mcp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcptoken',
            name='salt',
            field=models.CharField(blank=True, editable=False, help_text='Salt used for token hashing', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='mcptoken',
            name='token_hash',
            field=models.CharField(blank=True, editable=False, help_text='SHA-256 hash of the authentication token', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mcptoken',
            name='token',
            field=models.CharField(blank=True, editable=False, help_text='DEPRECATED: Token is now hashed. This field will be removed in future versions.', max_length=64, null=True, unique=True),
        ),
    ]
