# Generated by Django 6.0 on 2025-12-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_admin_mcp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcptoken',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups this token belongs to for permission management', related_name='mcp_tokens', to='auth.group'),
        ),
        migrations.AddField(
            model_name='mcptoken',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions granted to this token', related_name='mcp_tokens', to='auth.permission'),
        ),
    ]
