# Generated by Django 6.0.1 on 2026-09-15 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_mcp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcptoken',
            name='user',
            field=models.ForeignKey(help_text="Caps the token's permissions (the token can never exceed this user's access) and is the audit identity actions are logged under", on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
