# Generated by Django 6.0.1 on 2026-01-24 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_admin_mcp', '0002_mcptoken_salt_mcptoken_token_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mcptoken',
            index=models.Index(fields=['is_active', 'token_hash'], name='mcp_token_active_hash_idx'),
        ),
    ]
