# Generated by Django 6.0 on 2025-12-22 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_admin_mcp', '0002_mcptoken_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mcptoken',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups this token belongs to for permission management', related_name='mcp_tokens', to='auth.group'),
        ),
        migrations.AddField(
            model_name='mcptoken',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions granted to this token', related_name='mcp_tokens', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='mcptoken',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Associate this token with a Django user for permission checking', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
